# Generated by Django 5.1 on 2024-09-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dostavka',
            old_name='cena',
            new_name='kuda',
        ),
        migrations.RenameField(
            model_name='dostavka',
            old_name='name',
            new_name='tarif',
        ),
    ]
