# Generated by Django 5.0.6 on 2024-06-04 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opisanie', models.CharField(max_length=512)),
                ('catborn', models.DateTimeField()),
                ('okras', models.CharField(max_length=512)),
                ('poroda', models.CharField(max_length=512)),
                ('namecat', models.CharField(max_length=512)),
                ('polcat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=512)),
                ('done', models.BooleanField(default=False)),
                ('category', models.CharField(default='#ff0000')),
            ],
        ),
    ]
