# Generated by Django 5.0.6 on 2024-05-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opisanie', models.CharField(max_length=512)),
                ('catborn', models.DateTimeField()),
                ('okras', models.CharField(max_length=512)),
                ('poroda', models.CharField(max_length=512)),
                ('namecat', models.CharField(max_length=512)),
                ('polcat', models.BooleanField(default=False)),
            ],
        ),
    ]
